<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\image\Entity\ImageStyle;
use VK\Client\VKApiClient;
use VK\Exceptions\VKApiException;
use VK\Exceptions\VKClientException;

/**
 * Implements hook_entity_insert().
 * After inserting node, check if active VK status from Config form and publish node to the Company group wall in VK
 * For testing only update - crossposting_vk_entity_update
 */

function crossposting_vk_entity_insert(EntityInterface $entity) {
  
  $config = \Drupal::config('crossposting_vk.settings');
  $key = $config->get('key');
  $owner_id = $config->get('owner_id');
  $version = $config->get('version');
  $active = $entity->field_crossposting_vk->value;

  if ($active && $entity->getEntityTypeId() == 'node' && $entity->bundle() == 'news') {
    $id = $entity->id();
    $title = $entity->title->value;
    $node_url = $entity->toUrl('canonical', ['absolute' => TRUE])->toString();
    $body = strip_tags($entity->body->value);
    $textStrip = str_replace("&nbsp;", '', $body);
    $message = "{$title}\n\n{$textStrip}";
    // $image = $entity->field_image->entity->uri->value;
    // $style = ImageStyle::load('wide');
    // $thumb = $style->buildUrl($image);

    $access_token = \Drupal::service('key.repository')->getKey($key)->getKeyValue();

    $vk = new VKApiClient();

    $params = array(
      'owner_id' => '-' . $owner_id,
      'message' => $message,
      'form_group' => 1,
      'attachments' => $node_url
    );

    try {
      // Send message to Group
      $vk->wall()->post($access_token, $params);

      // if response "ok" set good message
      \Drupal::messenger()->addStatus(t('Post successfully posted on the wall.'));

    } catch (VKApiException $e) {
      // handle VK API exceptions
      \Drupal::messenger()->addStatus(t('VK API error: ') . $e->getMessage());
    } catch (VKClientException $e) {
      // handle VK client exceptions
      \Drupal::messenger()->addStatus(t('VK client error: ') . $e->getMessage());
    }
  }
}